import os
import asyncio
from dotenv import load_dotenv
from autogen_agentchat.agents import AssistantAgent
from autogen_ext.models.openai import OpenAIChatCompletionClient
import git

# --- Load .env ---
load_dotenv()
api_key = os.getenv("OPENAI_API_KEY")
if not api_key:
    raise ValueError("OPENAI_API_KEY not found in .env file!")

# --- Config ---
REPO_PATH = os.path.dirname(os.path.abspath(__file__))
REPO_URL = "https://github.com/victorrathore/autogen-github-site.git"  # replace with your repo
INDEX_FILE = os.path.join(REPO_PATH, "index.html")

# --- Ensure index.html exists ---
if not os.path.exists(INDEX_FILE):
    with open(INDEX_FILE, "w") as f:
        f.write("<!DOCTYPE html><html><body><h1>Hello from Autogen Agent!</h1></body></html>")

# --- Clone or init repo ---
if not os.path.exists(os.path.join(REPO_PATH, ".git")):
    repo = git.Repo.init(REPO_PATH)
    # Create remote only if we just initialized
    repo.create_remote("origin", REPO_URL)
else:
    repo = git.Repo(REPO_PATH)

# --- Autogen Agent prompt ---
prompt = """
Generate a GitHub Actions workflow YAML file for a static HTML site.
The workflow should:
1. Trigger on push to main branch.
2. Checkout the code.
3. Deploy the site automatically to GitHub Pages.
4. Schedule it to run daily at 6 PM IST.
Return only valid YAML content.
"""

# --- Initialize Agent ---
model_client = OpenAIChatCompletionClient(model="gpt-4o", api_key=api_key)
agent = AssistantAgent(
    name="assistant",
    model_client=model_client
)

async def main():
    # --- Generate workflow asynchronously ---
    workflow_task = await agent.run(task=prompt)
    workflow_text = workflow_task.messages[-1].content  # Extract final response

    # --- Save workflow ---
    workflow_dir = os.path.join(REPO_PATH, ".github", "workflows")
    os.makedirs(workflow_dir, exist_ok=True)

    workflow_file = os.path.join(workflow_dir, "deploy.yml")
    with open(workflow_file, "w") as f:
        f.write(workflow_text)

    print("Workflow generated at:", workflow_file)

    # --- Git commit & push ---
    repo.git.add(all=True)
    repo.index.commit("Add index.html and autogenerated GitHub Actions workflow")

    # Ensure remote 'origin' exists
    if "origin" not in [r.name for r in repo.remotes]:
        origin = repo.create_remote("origin", REPO_URL)
    else:
        origin = repo.remote(name="origin")

    origin.push(refspec="main:main")
    print("Workflow pushed to GitHub")

# --- Run the async main ---
asyncio.run(main())
